version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"

  api-test:
    build: .
    depends_on:
      - db
    environment:
      NODE_ENV: test
      DATABASE_URL: postgres://myuser:mypassword@db:5432/mydatabase
    command: >
      sh -c "bun test spec/e2e/happy-jounery.spec.ts &&
             bun test spec/e2e/create-block.spec.ts &&
             bun test spec/e2e/rollback.spec.ts"
volumes:
  db_data:
